### PR TITLE
Expenses

### PR DESCRIPTION
**Pull request by LuisCastilloKC**
Add Expense Component. install Bootstrap 5, remove the default code, and started the expenses form.

### CODE REVIEW

**Review by Rayhan1998 — APPROVED** [review]
I would move expenses to the component folder if an independent or reusable component or move to a folder called pages if a page.

**Review by Rayhan1998 — CHANGES_REQUESTED** [review]
Hey Luis, your branch is behind in development. Can you pull in the changes in development to your branch

**Comment by LuisCastilloKC** [comment]
Ok, let me fix it.

**Review by sage-watterworth — APPROVED** [review]

**Review by srcntuna — APPROVED** [review]

**Review by LuisCastilloKC — COMMENTED** [review]
reviewed

**Pull request merged**
